name: Test
on:
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        go:
          - '1.17.x'
          - '1.18.x'
          - '1.19.x'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Download Dependencies
        run: go get -v -t ./...

      - name: Go vet
        run: go vet ./...

      - name: Run Tests
        run: go test -v -race ./...